# Generated by Django 3.0.4 on 2020-03-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profileImageLink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotifyId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
