# Generated by Django 3.0.4 on 2020-03-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20200329_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotifyId',
        ),
        migrations.AddField(
            model_name='song',
            name='songUrl',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
