# Generated by Django 3.0.4 on 2020-03-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20200329_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='searchedSpotify',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
