# Generated by Django 3.0.4 on 2020-03-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_artist_searchedspotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='searchedSpotify',
            field=models.BooleanField(default=False),
        ),
    ]
